language: python
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
  - "3.8-dev"  # 3.8 development branch
  - "nightly"  # nightly build

jobs:
  include:
    - stage: style
      install:
       - pip install pycodestyle
       - pip install pydocstyle
      script:
        - make pycodestyle
        - make pydocstyle
    - stage: unit tests
      install:
        - pip install pytest-cov
        - pip install -r requirements.txt
      script:
        - pytest -v --cov=insights_sha_extractor

stages:
  - style
  - unit tests
