{
 "title": "CCX Insights SHA Extractor",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": "ccx-data-pipeline-stage,ccx-data-pipeline-prod"
   }
  ]
 },
 "panels": [
  {
   "title": "Stats Watcher (Counters)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(ccx_consumer_received_total{namespace=\"$namespace\", service=\"ccx-sha-extractor-prometheus-exporter\"}[1m]))",
     "legendFormat": "received"
    },
    {
     "expr": "sum(increase(ccx_downloaded_total_count{namespace=\"$namespace\", service=\"ccx-sha-extractor-prometheus-exporter\"}[1m]))",
     "legendFormat": "downloaded"
    },
    {
     "expr": "sum(increase(ccx_engine_processed_total{namespace=\"$namespace\", service=\"ccx-sha-extractor-prometheus-exporter\"}[1m]))",
     "legendFormat": "processed"
    },
    {
     "expr": "sum(increase(ccx_published_total{namespace=\"$namespace\", service=\"ccx-sha-extractor-prometheus-exporter\"}[1m]))",
     "legendFormat": "published"
    },
    {
     "expr": "sum(increase(ccx_failures_total{namespace=\"$namespace\", service=\"ccx-sha-extractor-prometheus-exporter\"}[1m]))",
     "legendFormat": "failures"
    },
    {
     "expr": "sum(increase(ccx_not_handled_total{namespace=\"$namespace\", service=\"ccx-sha-extractor-prometheus-exporter\"}[1m]))",
     "legendFormat": "not handled"
    },
    {
     "expr": "sum(increase(ccx_engine_processed_timeout_total{namespace=\"$namespace\", service=\"ccx-sha-extractor-prometheus-exporter\"}[1m]))",
     "legendFormat": "engine timeouts"
    }
   ]
  },
  {
   "title": "Pods CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{namespace=\"$namespace\",pod=~\"ccx-sha-extractor-.*\"}[1m])) by (pod)\n"
    }
   ]
  },
  {
   "title": "Pods memory usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 23, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{namespace=\"$namespace\",pod=~\"ccx-sha-extractor-.*\"}) by (pod)"
    }
   ]
  },
  {
   "title": "Pods network in",
   "type": "graph",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{namespace=\"$namespace\", pod=~\"ccx-sha-extractor-.*\"}[1m])) by (pod)"
    }
   ]
  },
  {
   "title": "Pods network out",
   "type": "graph",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{namespace=\"$namespace\", pod=~\"ccx-sha-extractor-.*\"}[1m])) by (pod)"
    }
   ]
  },
  {
   "title": "Stats Watcher: Seconds to Process a Single Archive",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short", "label": "Number of Occurrences" }
   ],
   "targets": [
    {
     "expr": "sum by (le) (ccx_process_duration_seconds_bucket{namespace=\"$namespace\", service=\"ccx-sha-extractor-prometheus-exporter\", le=\"0.1\"})",
     "legendFormat": "( -Inf; 0.1 >"
    },
    {
     "expr": "sum by (le) (ccx_process_duration_seconds_bucket{namespace=\"$namespace\", service=\"ccx-sha-extractor-prometheus-exporter\", le=\"0.25\"}) - ignoring(le) sum by (le) (ccx_process_duration_seconds_bucket{namespace=\"$namespace\", service=\"ccx-sha-extractor-prometheus-exporter\", le=\"0.1\"})",
     "legendFormat": "( 0.1; 0.25 >"
    },
    {
     "expr": "sum by (le) (ccx_process_duration_seconds_bucket{namespace=\"$namespace\", service=\"ccx-sha-extractor-prometheus-exporter\", le=\"0.5\"}) - ignoring(le) sum by (le) (ccx_process_duration_seconds_bucket{namespace=\"$namespace\", service=\"ccx-sha-extractor-prometheus-exporter\", le=\"0.25\"})",
     "legendFormat": "( 0.25; 0.5 >"
    },
    {
     "expr": "sum by (le) (ccx_process_duration_seconds_bucket{namespace=\"$namespace\", service=\"ccx-sha-extractor-prometheus-exporter\", le=\"0.75\"}) - ignoring(le) sum by (le) (ccx_process_duration_seconds_bucket{namespace=\"$namespace\", service=\"ccx-sha-extractor-prometheus-exporter\", le=\"0.5\"})",
     "legendFormat": "( 0.5; 0.75 >"
    },
    {
     "expr": "sum by (le) (ccx_process_duration_seconds_bucket{namespace=\"$namespace\", service=\"ccx-sha-extractor-prometheus-exporter\", le=\"1.0\"}) - ignoring(le) sum by (le) (ccx_process_duration_seconds_bucket{namespace=\"$namespace\", service=\"ccx-sha-extractor-prometheus-exporter\", le=\"0.75\"})",
     "legendFormat": "( 0.75; 1.0 >"
    },
    {
     "expr": "sum by (le) (ccx_process_duration_seconds_bucket{namespace=\"$namespace\", service=\"ccx-sha-extractor-prometheus-exporter\", le=\"10.0\"}) - ignoring(le) sum by (le) (ccx_process_duration_seconds_bucket{namespace=\"$namespace\", service=\"ccx-sha-extractor-prometheus-exporter\", le=\"1.0\"})",
     "legendFormat": "( 1.0; 10.0 >"
    },
    {
     "expr": "sum by (le) (ccx_process_duration_seconds_bucket{namespace=\"$namespace\", service=\"ccx-sha-extractor-prometheus-exporter\", le=\"+Inf\"}) - ignoring(le) sum by (le) (ccx_process_duration_seconds_bucket{namespace=\"$namespace\", service=\"ccx-sha-extractor-prometheus-exporter\", le=\"10.0\"})",
     "legendFormat": "( 10.0; +Inf )"
    }
   ]
  },
  {
   "title": "Stats Watcher: Seconds to Download a Single Archive",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "short", "label": "Number of Occurrences" }
   ],
   "targets": [
    {
     "expr": "sum by (le) (ccx_download_duration_seconds_bucket{namespace=\"$namespace\", service=\"ccx-sha-extractor-prometheus-exporter\", le=\"0.1\"})",
     "legendFormat": "( -Inf; 0.1 >"
    },
    {
     "expr": "sum by (le) (ccx_download_duration_seconds_bucket{namespace=\"$namespace\", service=\"ccx-sha-extractor-prometheus-exporter\",le=\"0.25\"}) - ignoring(le) sum by (le) (ccx_download_duration_seconds_bucket{namespace=\"$namespace\", service=\"ccx-sha-extractor-prometheus-exporter\", le=\"0.1\"})",
     "legendFormat": "( 0.1; 0.25 >"
    },
    {
     "expr": "sum by (le) (ccx_download_duration_seconds_bucket{namespace=\"$namespace\", service=\"ccx-sha-extractor-prometheus-exporter\", le=\"0.5\"}) - ignoring(le) sum by (le) (ccx_download_duration_seconds_bucket{namespace=\"$namespace\", service=\"ccx-sha-extractor-prometheus-exporter\", le=\"0.25\"})",
     "legendFormat": "( 0.25; 0.5 >"
    },
    {
     "expr": "sum by (le) (ccx_download_duration_seconds_bucket{namespace=\"$namespace\", service=\"ccx-sha-extractor-prometheus-exporter\", le=\"0.75\"}) - ignoring(le) sum by (le) (ccx_download_duration_seconds_bucket{namespace=\"$namespace\",service=\"ccx-sha-extractor-prometheus-exporter\",  le=\"0.5\"})",
     "legendFormat": "( 0.5; 0.75 >"
    },
    {
     "expr": "sum by (le) (ccx_download_duration_seconds_bucket{namespace=\"$namespace\", service=\"ccx-sha-extractor-prometheus-exporter\", le=\"1.0\"}) - ignoring(le) sum by (le) (ccx_download_duration_seconds_bucket{namespace=\"$namespace\", service=\"ccx-sha-extractor-prometheus-exporter\",le=\"0.75\"})",
     "legendFormat": "( 0.75; 1.0 >"
    },
    {
     "expr": "sum by (le) (ccx_download_duration_seconds_bucket{namespace=\"$namespace\", service=\"ccx-sha-extractor-prometheus-exporter\", le=\"10.0\"}) - ignoring(le) sum by (le) (ccx_download_duration_seconds_bucket{namespace=\"$namespace\", service=\"ccx-sha-extractor-prometheus-exporter\",le=\"1.0\"})",
     "legendFormat": "( 1.0; 10.0 >"
    },
    {
     "expr": "sum by (le) (ccx_download_duration_seconds_bucket{namespace=\"$namespace\", service=\"ccx-sha-extractor-prometheus-exporter\", le=\"+Inf\"}) - ignoring(le) sum by (le) (ccx_download_duration_seconds_bucket{namespace=\"$namespace\", service=\"ccx-sha-extractor-prometheus-exporter\", le=\"10.0\"})",
     "legendFormat": "( 10.0; +Inf )"
    }
   ]
  },
  {
   "title": "Stats Watcher: Seconds to Publish a Single Archive",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short", "label": "Number of Occurrences" }
   ],
   "targets": [
    {
     "expr": "sum by (le) (ccx_publish_duration_seconds_bucket{namespace=\"$namespace\", service=\"ccx-sha-extractor-prometheus-exporter\", le=\"0.005\"})",
     "legendFormat": "( -Inf; 0.005 >"
    },
    {
     "expr": "sum by (le) (ccx_publish_duration_seconds_bucket{namespace=\"$namespace\", service=\"ccx-sha-extractor-prometheus-exporter\", le=\"0.01\"}) - ignoring(le) sum by (le) (ccx_publish_duration_seconds_bucket{namespace=\"$namespace\", service=\"ccx-sha-extractor-prometheus-exporter\", le=\"0.005\"})",
     "legendFormat": "( 0.005; 0.01 >"
    },
    {
     "expr": "sum by (le) (ccx_publish_duration_seconds_bucket{namespace=\"$namespace\", service=\"ccx-sha-extractor-prometheus-exporter\",  le=\"0.025\"}) - ignoring(le) sum by (le) (ccx_publish_duration_seconds_bucket{namespace=\"$namespace\", service=\"ccx-sha-extractor-prometheus-exporter\", le=\"0.01\"})",
     "legendFormat": "( 0.01; 0.025 >"
    },
    {
     "expr": "sum by (le) (ccx_publish_duration_seconds_bucket{namespace=\"$namespace\", service=\"ccx-sha-extractor-prometheus-exporter\", le=\"0.1\"}) - ignoring(le) sum by (le) (ccx_publish_duration_seconds_bucket{namespace=\"$namespace\", service=\"ccx-sha-extractor-prometheus-exporter\",  le=\"0.025\"})",
     "legendFormat": "( 0.025; 0.1 >"
    },
    {
     "expr": "sum by (le) (ccx_publish_duration_seconds_bucket{namespace=\"$namespace\", service=\"ccx-sha-extractor-prometheus-exporter\", le=\"0.5\"}) - ignoring(le) sum by (le) (ccx_publish_duration_seconds_bucket{namespace=\"$namespace\", service=\"ccx-sha-extractor-prometheus-exporter\", le=\"0.1\"})",
     "legendFormat": "( 0.1; 0.5 >"
    },
    {
     "expr": "sum by (le) (ccx_publish_duration_seconds_bucket{namespace=\"$namespace\", service=\"ccx-sha-extractor-prometheus-exporter\", le=\"10.0\"}) - ignoring(le) sum by (le) (ccx_publish_duration_seconds_bucket{namespace=\"$namespace\", service=\"ccx-sha-extractor-prometheus-exporter\", le=\"0.5\"})",
     "legendFormat": "( 0.5; 10.0 >"
    },
    {
     "expr": "sum by (le) (ccx_publish_duration_seconds_bucket{namespace=\"$namespace\", service=\"ccx-sha-extractor-prometheus-exporter\", le=\"+Inf\"}) - ignoring(le) sum by (le) (ccx_publish_duration_seconds_bucket{namespace=\"$namespace\", service=\"ccx-sha-extractor-prometheus-exporter\", le=\"10.0\"})",
     "legendFormat": "( 10.0; +Inf )"
    }
   ]
  }
 ]
}