title: Insights SHA Extractor
description: SHA Extractor service exports SHAs of images
baseurl: /insights-sha-extractor
url: "https://redhatinsights.github.io"
repository: "RedHatInsights/insights-sha-extractor"

heading_anchors: true
search_enabled: false

footer_content: "Copyright &copy; 2024 Red Hat, Inc.</a>"

# Build settings
# markdown: kramdown
remote_theme: pmarsceill/just-the-docs
plugins:
  - jekyll-feed
  - jekyll-remote-theme

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/
  - sources.tmpl.md
