name: Run tests

on: [push, pull_request]

jobs:
  bdd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Retrieve Docker compose file
        run: wget -O docker-compose.yml https://raw.githubusercontent.com/RedHatInsights/insights-behavioral-spec/3b8546efa8c658f544df5c89e1165b25b0cdc32b/docker-compose.yml
      - name: Retrieve BDD runner
        run: wget -O bdd_runner.sh https://raw.githubusercontent.com/RedHatInsights/insights-behavioral-spec/3b8546efa8c658f544df5c89e1165b25b0cdc32b/run_in_docker.sh && chmod +x bdd_runner.sh
      - name: Run BDD
        run: ./bdd_runner.sh insights-sha-extractor-tests .
      - name: Set container ID as env
        if: always()
        run: echo "BDD_CONTAINER=$(docker ps | grep 'insights-behavioral-spec:latest' | cut -d ' ' -f 1)" >> $GITHUB_ENV
      - name: Debug
        if: always()
        run: docker exec -u root "$BDD_CONTAINER" /bin/bash -c "ls -R /insights-behavioral-spec/logs"
      - name: Copy logs from container to host
        if: always()
        run: docker cp "$BDD_CONTAINER:/insights-behavioral-spec/logs/insights_sha_extractor.log" .
      - name: Store service logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: store-logs
          path: insights_sha_extractor.log
