name: Linters
on:
  - push
  - pull_request

jobs:
  # Ruff replaces the many pre-commit checks like:
  # e.g. black, flake8, pyupgrade, pydocstyle
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: chartboost/ruff-action@v1

  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - uses: pre-commit/action@v3.0.1
